### ISSUE TITLE
Rozważenie możliwości wykorzystania symulatorów sieciowych

### ISSUE THREAD

**Issue by w-ku** [w-ku/TiirtProjekt#1]
Należy zapoznać się z frameworkami do symulacji sieciowych i ocenić ich przydatność w kontekście rozważanego problemu dostępu do sieci.

Symulatory do rozważenia:
- [ns-2](http://www.isi.edu/nsnam/ns/)
- [ns-3](http://www.nsnam.org/)
- [OMNeT++](http://omnetpp.org/)

**Comment by szkiecin** [comment]
bierzemy omnet ++

**Comment by pe-borkowski** [comment]
Jednak piszemy w Python'nie

**Comment by w-ku** [comment]
Zrezygnowano z wykorzystania istniejących frameworków.
