### ISSUE TITLE
Dopracowanie wstępu

### ISSUE THREAD

**Issue by w-ku** [w-ku/TiirtProjekt#32]
Należy dopracować wstęp, opierając się na uwagach z poprzednich zajęć.

**Comment by w-ku** [comment]
Nowa zasada: przed wysłaniem prowadzącemu, proszę wrzucić na grupę fb plik, który ma być wysłany. Im więcej osób go przejrzy, tym lepiej.

**Comment by bartekkucin** [comment]
Wstęp jest cały czas aktualizowany i link do niego znajduje się od początku ma grupie. Każdy może do niego zajrzeć i zweryfikować zawartość w dowolnej chwili.

**Comment by w-ku** [comment]
Owszem, lecz roboczy Google doc ze wstępem != plik wysłany prowadzącemu. Wydaje mi się, że standardy w obu przypadkach powinny być nieco inne.

**Comment by w-ku** [comment]
Można uznać, że wstęp został dopracowany w takim stopniu, jakim się dało.
