### ISSUE TITLE
Błąd przy uruchomieniu onOff.py

### ISSUE THREAD

**Issue by w-ku** [w-ku/TiirtProjekt#36]
> File "onOff.py", line 64, in generator_zgloszen
>     gen_on = tc.generate_onOff(ON)
> AttributeError: 'TokenGenerator' object has no attribute 'generate_onOff'

Hot fixem jest dodanie do generator.py:

```
def generate_onOff(self, t):
    return self.generate_ts(1.0/t)
```

Jednak nie mam pewności, czy takiej metody tam w ogóle nie było, czy też plik nie został uwzględniony w commicie.

**Comment by pe-borkowski** [comment]
Testowałem generator dla on/off i jak dla mnie powinien on wyglądać tak:

`def generate_onOff(self, On):
        x = (1.0/On)
        r = np.random.exponential(x)
        return r`

Bez tego dzielenia (x = (1.0/On)) wychodzą dziwne rzeczy - tyle że wartości są odwrócone (przy on=200 i off=2, on działa bardzo krótko a przerwy są długie)

**Comment by w-ku** [comment]
Ten bug odnosił się do wysypawania się programu, nie poprawności działania On/Off. Program już się nie wysypuje, więc ten wątek można zamknać.

Jednakże On/Off nie działa poprawnie. Napisałem wyjaśnienie w #34.
