### ISSUE TITLE
Przyspieszenie symulatora

### ISSUE THREAD

**Issue by w-ku** [w-ku/TiirtProjekt#37]
W tym momencie symulator działa wolno z powodu wykorzystania w nim sleep() dla dosyć długich okresów czasu. Jest to szczególnie uciążliwe w przypadku testów z:
- dużą wartością parametru accQty
- małą wartością V<sub>Z</sub>
- małą wartoscią &lambda;

---

Chyba dość prostym rozwiązaniem (niewymagającym dużych zmian w kodzie) byłoby przeskalowanie sekundy na 1/100 sekundy. Jednak trzeba uwzględnić następujące rzeczy:
- należy sprawdzić jak python radzi sobie ze sleepem dla małych wartości. Jeżeli długości snu będą obarczone dużym błędem, trzeba spróbować większe wartości. Nawet 1/20 sekundy będzie niezłym usprawnieniem (~20 razy szybsza symulacja).
- należy uwzględnić skalowanie przy obliczaniu czasów otrzymania/zaakceptowania zgłoszenia. Mimo że program zasypia na krótsze okresy czasu niż podane w jego parametrach, wynik musi być zgodny z parametrami zadynymi przez użytkownika.

**Comment by pe-borkowski** [comment]
Przy próbie przeskalowania czasu pojawiają się rozbieżności w prawdopodobieństwie odrzucenia - powodem prawdopodobnie jest rozjechanie się wątku napełniania wiadra z wątkiem generatora.

Zauważyłem zależność:
maksymalny dzielnik czasu = ACCQTY / 10

Czyli np. przy ACCQTY = 1000, możemy przyśpieszyć program maksymalnie 100x bez większych różnic w prawdopodobieństwie odrzucenia w porównaniu do działania symulatora bez przyśpieszenia.

**Comment by w-ku** [comment]
W jaki sposób ACCQTY wpływa na dzielnik czasu? Przecież ACCQTY określa tylko, po ilu zaakceptowanych zgłoszeniach symulacja ma się zakończyć. Nie wpływa na odstępy czasu między wydarzeniami zachodzącymi w systemie.

Wg mnie symulator nadal działa dosyć wolno, ale najważniejsze jest zdanie grupy robiącej pomiary.

**Comment by pe-borkowski** [comment]
Wydaje mi się że im większe ACCQTY tym większy błąd działania programu - bo trwa dłużej więc błędów jest więcej. ACCQTY / 10 daje nam akceptowalny błąd i moim zdaniem akceptowalny czas działania symulatora (z 30 minut przyspieszyłem do 3 minut).

**Comment by w-ku** [comment]
Ale to by świadczyło, że program źle działa, ponieważ generalnie większe ACCQTY będzie sprawiać, że symulator będzie się dłużej znajdować w stanie stabilności, a przez to D i P_B będą bardziej zbliżone do faktycznych średnich wartości tych wskaźników dla wielu uruchomień symulacji dla tych samych danych.

Symulator osiągnie czas stabilności, kiedy np. dla przypadku rozkładu Poissona, z ustalonym małym V_Z i dużą LAMBDą, wiadro zostanie opróżnione. Wtedy P_B będzie uzależnione od V_Z, z kolei D będzie uzależnione od L_Q do końca trwania symulacji. Jeżeli mamy małe ACCQTY, to dla ogromnej rzeszy przypadków testowych nigdy nawet nie osiągniemy stanu stabilności, przez co wyniki będą się bardzo różnić dla kolejnych odpaleń symulatora dla tych samych danych.

**Comment by w-ku** [comment]
Próby przyspieszenia zostały podjęte, powód niewystarczającego powodzenia został opisany w opisie implementacji w raporcie.
