### ISSUE TITLE
Przygotowanie opisu implementacji opartej na wątkach

### ISSUE THREAD

**Issue by w-ku** [w-ku/TiirtProjekt#39]
W punkcie 7. raportu (**Projekt, implementacja oraz sposoby testowania symulatora**) powinien się znaleźć opis implementacji symulatora.

W ramach projektu powstały dwa symulatory:
- [jeden oparty na wątkach](https://github.com/w-ku/TiirtProjekt),
- [drugi bez wykorzystania wątków](https://github.com/w-ku/sqss),

oba napisane w Pythonie bez wykorzystania dodatkowych blibliotek (oprócz numpy).

W raporcie należy uwzględnić opis obu implementacji, napotkane trudności, łatwość rozszerzania, wnioski. To zadanie tyczy się wykonania opisu implementacji z wykorzystaniem wątków.

**Comment by pe-borkowski** [comment]
Wstępny opis implementacji:
https://docs.google.com/document/d/1PdMrWyQ1MJruQIUGFNkWsbM0nKNaN8k7Shmk1xGoiR8/edit?usp=sharing
Proszę o komentarz do tego co zostało napisane oraz o ewentualne podpowiedzi co można by jeszcze uwzględnić.

**Comment by w-ku** [comment]
Opis został dodany do raportu.
